/* Copyright 2023 Dual Tachyon
 * https://github.com/DualTachyon
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef HARDWARE_DP32G030_SYSCON_H
#define HARDWARE_DP32G030_SYSCON_H

#if !defined(__ASSEMBLY__)
#include <stdint.h>
#endif

/* -------- SYSCON -------- */
#define SYSCON_BASE_ADDR                          0x40000000U
#define SYSCON_BASE_SIZE                          0x00000800U

#define SYSCON_CLK_SEL_ADDR                       (SYSCON_BASE_ADDR + 0x0000U)
#define SYSCON_CLK_SEL                            (*(volatile uint32_t *)SYSCON_CLK_SEL_ADDR)
#define SYSCON_CLK_SEL_SYS_CLK_SEL_SHIFT          0
#define SYSCON_CLK_SEL_SYS_CLK_SEL_WIDTH          1
#define SYSCON_CLK_SEL_SYS_CLK_SEL_MASK           (((1U << SYSCON_CLK_SEL_SYS_CLK_SEL_WIDTH) - 1U) << SYSCON_CLK_SEL_SYS_CLK_SEL_SHIFT)
#define SYSCON_CLK_SEL_SYS_CLK_SEL_RCHF           (0U << SYSCON_CLK_SEL_SYS_CLK_SEL_SHIFT)
#define SYSCON_CLK_SEL_SYS_CLK_SEL_DIV_CLK        (1U << SYSCON_CLK_SEL_SYS_CLK_SEL_SHIFT)

#define SYSCON_CLK_SEL_DIV_CLK_SEL_SHIFT          1
#define SYSCON_CLK_SEL_DIV_CLK_SEL_WIDTH          3
#define SYSCON_CLK_SEL_DIV_CLK_SEL_MASK           (((1U << SYSCON_CLK_SEL_DIV_CLK_SEL_WIDTH) - 1U) << SYSCON_CLK_SEL_DIV_CLK_SEL_SHIFT)
#define SYSCON_CLK_SEL_DIV_CLK_SEL_1              (0U << SYSCON_CLK_SEL_DIV_CLK_SEL_SHIFT)
#define SYSCON_CLK_SEL_DIV_CLK_SEL_2              (1U << SYSCON_CLK_SEL_DIV_CLK_SEL_SHIFT)
#define SYSCON_CLK_SEL_DIV_CLK_SEL_4              (2U << SYSCON_CLK_SEL_DIV_CLK_SEL_SHIFT)
#define SYSCON_CLK_SEL_DIV_CLK_SEL_8              (3U << SYSCON_CLK_SEL_DIV_CLK_SEL_SHIFT)
#define SYSCON_CLK_SEL_DIV_CLK_SEL_16             (4U << SYSCON_CLK_SEL_DIV_CLK_SEL_SHIFT)
#define SYSCON_CLK_SEL_DIV_CLK_SEL_32             (5U << SYSCON_CLK_SEL_DIV_CLK_SEL_SHIFT)

#define SYSCON_CLK_SEL_SRC_CLK_SEL_SHIFT          4
#define SYSCON_CLK_SEL_SRC_CLK_SEL_WIDTH          3
#define SYSCON_CLK_SEL_SRC_CLK_SEL_MASK           (((1U << SYSCON_CLK_SEL_SRC_CLK_SEL_WIDTH) - 1U) << SYSCON_CLK_SEL_SRC_CLK_SEL_SHIFT)
#define SYSCON_CLK_SEL_SRC_CLK_SEL_RCHF           (0U << SYSCON_CLK_SEL_SRC_CLK_SEL_SHIFT)
#define SYSCON_CLK_SEL_SRC_CLK_SEL_RCLF           (1U << SYSCON_CLK_SEL_SRC_CLK_SEL_SHIFT)
#define SYSCON_CLK_SEL_SRC_CLK_SEL_XTAH           (2U << SYSCON_CLK_SEL_SRC_CLK_SEL_SHIFT)
#define SYSCON_CLK_SEL_SRC_CLK_SEL_XTAL           (3U << SYSCON_CLK_SEL_SRC_CLK_SEL_SHIFT)
#define SYSCON_CLK_SEL_SRC_CLK_SEL_PLL            (4U << SYSCON_CLK_SEL_SRC_CLK_SEL_SHIFT)

#define SYSCON_DIV_CLK_GATE_ADDR                  (SYSCON_BASE_ADDR + 0x0004U)
#define SYSCON_DIV_CLK_GATE                       (*(volatile uint32_t *)SYSCON_DIV_CLK_GATE_ADDR)
#define SYSCON_DIV_CLK_GATE_DIV_CLK_GATE_SHIFT    1
#define SYSCON_DIV_CLK_GATE_DIV_CLK_GATE_WIDTH    1
#define SYSCON_DIV_CLK_GATE_DIV_CLK_GATE_MASK     (((1U << SYSCON_DIV_CLK_GATE_DIV_CLK_GATE_WIDTH) - 1U) << SYSCON_DIV_CLK_GATE_DIV_CLK_GATE_SHIFT)
#define SYSCON_DIV_CLK_GATE_DIV_CLK_GATE_DISABLE  (0U << SYSCON_DIV_CLK_GATE_DIV_CLK_GATE_SHIFT)
#define SYSCON_DIV_CLK_GATE_DIV_CLK_GATE_ENABLE   (1U << SYSCON_DIV_CLK_GATE_DIV_CLK_GATE_SHIFT)

#define SYSCON_DEV_CLK_GATE_ADDR                  (SYSCON_BASE_ADDR + 0x0008U)
#define SYSCON_DEV_CLK_GATE                       (*(volatile uint32_t *)SYSCON_DEV_CLK_GATE_ADDR)
#define SYSCON_DEV_CLK_GATE_GPIOA_SHIFT           0
#define SYSCON_DEV_CLK_GATE_GPIOA_WIDTH           1
#define SYSCON_DEV_CLK_GATE_GPIOA_MASK            (((1U << SYSCON_DEV_CLK_GATE_GPIOA_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_GPIOA_SHIFT)
#define SYSCON_DEV_CLK_GATE_GPIOA_DISABLE         (0U << SYSCON_DEV_CLK_GATE_GPIOA_SHIFT)
#define SYSCON_DEV_CLK_GATE_GPIOA_ENABLE          (1U << SYSCON_DEV_CLK_GATE_GPIOA_SHIFT)

#define SYSCON_DEV_CLK_GATE_GPIOB_SHIFT           1
#define SYSCON_DEV_CLK_GATE_GPIOB_WIDTH           1
#define SYSCON_DEV_CLK_GATE_GPIOB_MASK            (((1U << SYSCON_DEV_CLK_GATE_GPIOB_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_GPIOB_SHIFT)
#define SYSCON_DEV_CLK_GATE_GPIOB_DISABLE         (0U << SYSCON_DEV_CLK_GATE_GPIOB_SHIFT)
#define SYSCON_DEV_CLK_GATE_GPIOB_ENABLE          (1U << SYSCON_DEV_CLK_GATE_GPIOB_SHIFT)

#define SYSCON_DEV_CLK_GATE_GPIOC_SHIFT           2
#define SYSCON_DEV_CLK_GATE_GPIOC_WIDTH           1
#define SYSCON_DEV_CLK_GATE_GPIOC_MASK            (((1U << SYSCON_DEV_CLK_GATE_GPIOC_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_GPIOC_SHIFT)
#define SYSCON_DEV_CLK_GATE_GPIOC_DISABLE         (0U << SYSCON_DEV_CLK_GATE_GPIOC_SHIFT)
#define SYSCON_DEV_CLK_GATE_GPIOC_ENABLE          (1U << SYSCON_DEV_CLK_GATE_GPIOC_SHIFT)

#define SYSCON_DEV_CLK_GATE_IIC0_SHIFT            4
#define SYSCON_DEV_CLK_GATE_IIC0_WIDTH            1
#define SYSCON_DEV_CLK_GATE_IIC0_MASK             (((1U << SYSCON_DEV_CLK_GATE_IIC0_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_IIC0_SHIFT)
#define SYSCON_DEV_CLK_GATE_IIC0_DISABLE          (0U << SYSCON_DEV_CLK_GATE_IIC0_SHIFT)
#define SYSCON_DEV_CLK_GATE_IIC0_ENABLE           (1U << SYSCON_DEV_CLK_GATE_IIC0_SHIFT)

#define SYSCON_DEV_CLK_GATE_IIC1_SHIFT            5
#define SYSCON_DEV_CLK_GATE_IIC1_WIDTH            1
#define SYSCON_DEV_CLK_GATE_IIC1_MASK             (((1U << SYSCON_DEV_CLK_GATE_IIC1_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_IIC1_SHIFT)
#define SYSCON_DEV_CLK_GATE_IIC1_DISABLE          (0U << SYSCON_DEV_CLK_GATE_IIC1_SHIFT)
#define SYSCON_DEV_CLK_GATE_IIC1_ENABLE           (1U << SYSCON_DEV_CLK_GATE_IIC1_SHIFT)

#define SYSCON_DEV_CLK_GATE_UART0_SHIFT           6
#define SYSCON_DEV_CLK_GATE_UART0_WIDTH           1
#define SYSCON_DEV_CLK_GATE_UART0_MASK            (((1U << SYSCON_DEV_CLK_GATE_UART0_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_UART0_SHIFT)
#define SYSCON_DEV_CLK_GATE_UART0_DISABLE         (0U << SYSCON_DEV_CLK_GATE_UART0_SHIFT)
#define SYSCON_DEV_CLK_GATE_UART0_ENABLE          (1U << SYSCON_DEV_CLK_GATE_UART0_SHIFT)

#define SYSCON_DEV_CLK_GATE_UART1_SHIFT           7
#define SYSCON_DEV_CLK_GATE_UART1_WIDTH           1
#define SYSCON_DEV_CLK_GATE_UART1_MASK            (((1U << SYSCON_DEV_CLK_GATE_UART1_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_UART1_SHIFT)
#define SYSCON_DEV_CLK_GATE_UART1_DISABLE         (0U << SYSCON_DEV_CLK_GATE_UART1_SHIFT)
#define SYSCON_DEV_CLK_GATE_UART1_ENABLE          (1U << SYSCON_DEV_CLK_GATE_UART1_SHIFT)

#define SYSCON_DEV_CLK_GATE_UART2_SHIFT           8
#define SYSCON_DEV_CLK_GATE_UART2_WIDTH           1
#define SYSCON_DEV_CLK_GATE_UART2_MASK            (((1U << SYSCON_DEV_CLK_GATE_UART2_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_UART2_SHIFT)
#define SYSCON_DEV_CLK_GATE_UART2_DISABLE         (0U << SYSCON_DEV_CLK_GATE_UART2_SHIFT)
#define SYSCON_DEV_CLK_GATE_UART2_ENABLE          (1U << SYSCON_DEV_CLK_GATE_UART2_SHIFT)

#define SYSCON_DEV_CLK_GATE_SPI0_SHIFT            10
#define SYSCON_DEV_CLK_GATE_SPI0_WIDTH            1
#define SYSCON_DEV_CLK_GATE_SPI0_MASK             (((1U << SYSCON_DEV_CLK_GATE_SPI0_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_SPI0_SHIFT)
#define SYSCON_DEV_CLK_GATE_SPI0_DISABLE          (0U << SYSCON_DEV_CLK_GATE_SPI0_SHIFT)
#define SYSCON_DEV_CLK_GATE_SPI0_ENABLE           (1U << SYSCON_DEV_CLK_GATE_SPI0_SHIFT)

#define SYSCON_DEV_CLK_GATE_SPI1_SHIFT            11
#define SYSCON_DEV_CLK_GATE_SPI1_WIDTH            1
#define SYSCON_DEV_CLK_GATE_SPI1_MASK             (((1U << SYSCON_DEV_CLK_GATE_SPI1_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_SPI1_SHIFT)
#define SYSCON_DEV_CLK_GATE_SPI1_DISABLE          (0U << SYSCON_DEV_CLK_GATE_SPI1_SHIFT)
#define SYSCON_DEV_CLK_GATE_SPI1_ENABLE           (1U << SYSCON_DEV_CLK_GATE_SPI1_SHIFT)

#define SYSCON_DEV_CLK_GATE_TIMER_BASE0_SHIFT     12
#define SYSCON_DEV_CLK_GATE_TIMER_BASE0_WIDTH     1
#define SYSCON_DEV_CLK_GATE_TIMER_BASE0_MASK      (((1U << SYSCON_DEV_CLK_GATE_TIMER_BASE0_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_TIMER_BASE0_SHIFT)
#define SYSCON_DEV_CLK_GATE_TIMER_BASE0_DISABLE   (0U << SYSCON_DEV_CLK_GATE_TIMER_BASE0_SHIFT)
#define SYSCON_DEV_CLK_GATE_TIMER_BASE0_ENABLE    (1U << SYSCON_DEV_CLK_GATE_TIMER_BASE0_SHIFT)

#define SYSCON_DEV_CLK_GATE_TIMER_BASE1_SHIFT     13
#define SYSCON_DEV_CLK_GATE_TIMER_BASE1_WIDTH     1
#define SYSCON_DEV_CLK_GATE_TIMER_BASE1_MASK      (((1U << SYSCON_DEV_CLK_GATE_TIMER_BASE1_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_TIMER_BASE1_SHIFT)
#define SYSCON_DEV_CLK_GATE_TIMER_BASE1_DISABLE   (0U << SYSCON_DEV_CLK_GATE_TIMER_BASE1_SHIFT)
#define SYSCON_DEV_CLK_GATE_TIMER_BASE1_ENABLE    (1U << SYSCON_DEV_CLK_GATE_TIMER_BASE1_SHIFT)

#define SYSCON_DEV_CLK_GATE_TIMER_BASE2_SHIFT     14
#define SYSCON_DEV_CLK_GATE_TIMER_BASE2_WIDTH     1
#define SYSCON_DEV_CLK_GATE_TIMER_BASE2_MASK      (((1U << SYSCON_DEV_CLK_GATE_TIMER_BASE2_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_TIMER_BASE2_SHIFT)
#define SYSCON_DEV_CLK_GATE_TIMER_BASE2_DISABLE   (0U << SYSCON_DEV_CLK_GATE_TIMER_BASE2_SHIFT)
#define SYSCON_DEV_CLK_GATE_TIMER_BASE2_ENABLE    (1U << SYSCON_DEV_CLK_GATE_TIMER_BASE2_SHIFT)

#define SYSCON_DEV_CLK_GATE_TIMER_PLUS0_SHIFT     15
#define SYSCON_DEV_CLK_GATE_TIMER_PLUS0_WIDTH     1
#define SYSCON_DEV_CLK_GATE_TIMER_PLUS0_MASK      (((1U << SYSCON_DEV_CLK_GATE_TIMER_PLUS0_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_TIMER_PLUS0_SHIFT)
#define SYSCON_DEV_CLK_GATE_TIMER_PLUS0_DISABLE   (0U << SYSCON_DEV_CLK_GATE_TIMER_PLUS0_SHIFT)
#define SYSCON_DEV_CLK_GATE_TIMER_PLUS0_ENABLE    (1U << SYSCON_DEV_CLK_GATE_TIMER_PLUS0_SHIFT)

#define SYSCON_DEV_CLK_GATE_TIMER_PLUS1_SHIFT     16
#define SYSCON_DEV_CLK_GATE_TIMER_PLUS1_WIDTH     1
#define SYSCON_DEV_CLK_GATE_TIMER_PLUS1_MASK      (((1U << SYSCON_DEV_CLK_GATE_TIMER_PLUS1_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_TIMER_PLUS1_SHIFT)
#define SYSCON_DEV_CLK_GATE_TIMER_PLUS1_DISABLE   (0U << SYSCON_DEV_CLK_GATE_TIMER_PLUS1_SHIFT)
#define SYSCON_DEV_CLK_GATE_TIMER_PLUS1_ENABLE    (1U << SYSCON_DEV_CLK_GATE_TIMER_PLUS1_SHIFT)

#define SYSCON_DEV_CLK_GATE_PWM_BASE0_SHIFT       17
#define SYSCON_DEV_CLK_GATE_PWM_BASE0_WIDTH       1
#define SYSCON_DEV_CLK_GATE_PWM_BASE0_MASK        (((1U << SYSCON_DEV_CLK_GATE_PWM_BASE0_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_PWM_BASE0_SHIFT)
#define SYSCON_DEV_CLK_GATE_PWM_BASE0_DISABLE     (0U << SYSCON_DEV_CLK_GATE_PWM_BASE0_SHIFT)
#define SYSCON_DEV_CLK_GATE_PWM_BASE0_ENABLE      (1U << SYSCON_DEV_CLK_GATE_PWM_BASE0_SHIFT)

#define SYSCON_DEV_CLK_GATE_PWM_BASE1_SHIFT       18
#define SYSCON_DEV_CLK_GATE_PWM_BASE1_WIDTH       1
#define SYSCON_DEV_CLK_GATE_PWM_BASE1_MASK        (((1U << SYSCON_DEV_CLK_GATE_PWM_BASE1_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_PWM_BASE1_SHIFT)
#define SYSCON_DEV_CLK_GATE_PWM_BASE1_DISABLE     (0U << SYSCON_DEV_CLK_GATE_PWM_BASE1_SHIFT)
#define SYSCON_DEV_CLK_GATE_PWM_BASE1_ENABLE      (1U << SYSCON_DEV_CLK_GATE_PWM_BASE1_SHIFT)

#define SYSCON_DEV_CLK_GATE_PWM_PLUS0_SHIFT       20
#define SYSCON_DEV_CLK_GATE_PWM_PLUS0_WIDTH       1
#define SYSCON_DEV_CLK_GATE_PWM_PLUS0_MASK        (((1U << SYSCON_DEV_CLK_GATE_PWM_PLUS0_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_PWM_PLUS0_SHIFT)
#define SYSCON_DEV_CLK_GATE_PWM_PLUS0_DISABLE     (0U << SYSCON_DEV_CLK_GATE_PWM_PLUS0_SHIFT)
#define SYSCON_DEV_CLK_GATE_PWM_PLUS0_ENABLE      (1U << SYSCON_DEV_CLK_GATE_PWM_PLUS0_SHIFT)

#define SYSCON_DEV_CLK_GATE_PWM_PLUS1_SHIFT       21
#define SYSCON_DEV_CLK_GATE_PWM_PLUS1_WIDTH       1
#define SYSCON_DEV_CLK_GATE_PWM_PLUS1_MASK        (((1U << SYSCON_DEV_CLK_GATE_PWM_PLUS1_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_PWM_PLUS1_SHIFT)
#define SYSCON_DEV_CLK_GATE_PWM_PLUS1_DISABLE     (0U << SYSCON_DEV_CLK_GATE_PWM_PLUS1_SHIFT)
#define SYSCON_DEV_CLK_GATE_PWM_PLUS1_ENABLE      (1U << SYSCON_DEV_CLK_GATE_PWM_PLUS1_SHIFT)

#define SYSCON_DEV_CLK_GATE_RTC_SHIFT             22
#define SYSCON_DEV_CLK_GATE_RTC_WIDTH             1
#define SYSCON_DEV_CLK_GATE_RTC_MASK              (((1U << SYSCON_DEV_CLK_GATE_RTC_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_RTC_SHIFT)
#define SYSCON_DEV_CLK_GATE_RTC_DISABLE           (0U << SYSCON_DEV_CLK_GATE_RTC_SHIFT)
#define SYSCON_DEV_CLK_GATE_RTC_ENABLE            (1U << SYSCON_DEV_CLK_GATE_RTC_SHIFT)

#define SYSCON_DEV_CLK_GATE_IWDT_SHIFT            23
#define SYSCON_DEV_CLK_GATE_IWDT_WIDTH            1
#define SYSCON_DEV_CLK_GATE_IWDT_MASK             (((1U << SYSCON_DEV_CLK_GATE_IWDT_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_IWDT_SHIFT)
#define SYSCON_DEV_CLK_GATE_IWDT_DISABLE          (0U << SYSCON_DEV_CLK_GATE_IWDT_SHIFT)
#define SYSCON_DEV_CLK_GATE_IWDT_ENABLE           (1U << SYSCON_DEV_CLK_GATE_IWDT_SHIFT)

#define SYSCON_DEV_CLK_GATE_WWDT_SHIFT            24
#define SYSCON_DEV_CLK_GATE_WWDT_WIDTH            1
#define SYSCON_DEV_CLK_GATE_WWDT_MASK             (((1U << SYSCON_DEV_CLK_GATE_WWDT_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_WWDT_SHIFT)
#define SYSCON_DEV_CLK_GATE_WWDT_DISABLE          (0U << SYSCON_DEV_CLK_GATE_WWDT_SHIFT)
#define SYSCON_DEV_CLK_GATE_WWDT_ENABLE           (1U << SYSCON_DEV_CLK_GATE_WWDT_SHIFT)

#define SYSCON_DEV_CLK_GATE_SARADC_SHIFT          25
#define SYSCON_DEV_CLK_GATE_SARADC_WIDTH          1
#define SYSCON_DEV_CLK_GATE_SARADC_MASK           (((1U << SYSCON_DEV_CLK_GATE_SARADC_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_SARADC_SHIFT)
#define SYSCON_DEV_CLK_GATE_SARADC_DISABLE        (0U << SYSCON_DEV_CLK_GATE_SARADC_SHIFT)
#define SYSCON_DEV_CLK_GATE_SARADC_ENABLE         (1U << SYSCON_DEV_CLK_GATE_SARADC_SHIFT)

#define SYSCON_DEV_CLK_GATE_CRC_SHIFT             27
#define SYSCON_DEV_CLK_GATE_CRC_WIDTH             1
#define SYSCON_DEV_CLK_GATE_CRC_MASK              (((1U << SYSCON_DEV_CLK_GATE_CRC_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_CRC_SHIFT)
#define SYSCON_DEV_CLK_GATE_CRC_DISABLE           (0U << SYSCON_DEV_CLK_GATE_CRC_SHIFT)
#define SYSCON_DEV_CLK_GATE_CRC_ENABLE            (1U << SYSCON_DEV_CLK_GATE_CRC_SHIFT)

#define SYSCON_DEV_CLK_GATE_AES_SHIFT             28
#define SYSCON_DEV_CLK_GATE_AES_WIDTH             1
#define SYSCON_DEV_CLK_GATE_AES_MASK              (((1U << SYSCON_DEV_CLK_GATE_AES_WIDTH) - 1U) << SYSCON_DEV_CLK_GATE_AES_SHIFT)
#define SYSCON_DEV_CLK_GATE_AES_DISABLE           (0U << SYSCON_DEV_CLK_GATE_AES_SHIFT)
#define SYSCON_DEV_CLK_GATE_AES_ENABLE            (1U << SYSCON_DEV_CLK_GATE_AES_SHIFT)

#define SYSCON_RC_FREQ_DELTA_ADDR                 (SYSCON_BASE_ADDR + 0x0078U)
#define SYSCON_RC_FREQ_DELTA                      (*(volatile uint32_t *)SYSCON_RC_FREQ_DELTA_ADDR)
#define SYSCON_RC_FREQ_DELTA_RCLF_DELTA_SHIFT     0
#define SYSCON_RC_FREQ_DELTA_RCLF_DELTA_WIDTH     10
#define SYSCON_RC_FREQ_DELTA_RCLF_DELTA_MASK      (((1U << SYSCON_RC_FREQ_DELTA_RCLF_DELTA_WIDTH) - 1U) << SYSCON_RC_FREQ_DELTA_RCLF_DELTA_SHIFT)
#define SYSCON_RC_FREQ_DELTA_RCLF_SIG_SHIFT       10
#define SYSCON_RC_FREQ_DELTA_RCLF_SIG_WIDTH       1
#define SYSCON_RC_FREQ_DELTA_RCLF_SIG_MASK        (((1U << SYSCON_RC_FREQ_DELTA_RCLF_SIG_WIDTH) - 1U) << SYSCON_RC_FREQ_DELTA_RCLF_SIG_SHIFT)
#define SYSCON_RC_FREQ_DELTA_RCHF_DELTA_SHIFT     11
#define SYSCON_RC_FREQ_DELTA_RCHF_DELTA_WIDTH     20
#define SYSCON_RC_FREQ_DELTA_RCHF_DELTA_MASK      (((1U << SYSCON_RC_FREQ_DELTA_RCHF_DELTA_WIDTH) - 1U) << SYSCON_RC_FREQ_DELTA_RCHF_DELTA_SHIFT)
#define SYSCON_RC_FREQ_DELTA_RCHF_SIG_SHIFT       31
#define SYSCON_RC_FREQ_DELTA_RCHF_SIG_WIDTH       1
#define SYSCON_RC_FREQ_DELTA_RCHF_SIG_MASK        (((1U << SYSCON_RC_FREQ_DELTA_RCHF_SIG_WIDTH) - 1U) << SYSCON_RC_FREQ_DELTA_RCHF_SIG_SHIFT)

#define SYSCON_VREF_VOLT_DELTA_ADDR               (SYSCON_BASE_ADDR + 0x007CU)
#define SYSCON_VREF_VOLT_DELTA                    (*(volatile uint32_t *)SYSCON_VREF_VOLT_DELTA_ADDR)
#define SYSCON_CHIP_ID0_ADDR                      (SYSCON_BASE_ADDR + 0x0080U)
#define SYSCON_CHIP_ID0                           (*(volatile uint32_t *)SYSCON_CHIP_ID0_ADDR)
#define SYSCON_CHIP_ID1_ADDR                      (SYSCON_BASE_ADDR + 0x0084U)
#define SYSCON_CHIP_ID1                           (*(volatile uint32_t *)SYSCON_CHIP_ID1_ADDR)
#define SYSCON_CHIP_ID2_ADDR                      (SYSCON_BASE_ADDR + 0x0088U)
#define SYSCON_CHIP_ID2                           (*(volatile uint32_t *)SYSCON_CHIP_ID2_ADDR)
#define SYSCON_CHIP_ID3_ADDR                      (SYSCON_BASE_ADDR + 0x008CU)
#define SYSCON_CHIP_ID3                           (*(volatile uint32_t *)SYSCON_CHIP_ID3_ADDR)


#endif

