#ifndef BK4819_REGS_H
#define BK4819_REGS_H

enum BK4819_REGISTER_t {
	REG_00                                                                 = 0x00U,
	REG_06                                                                 = 0x06U,
	REG_07_CTC_FREQUENCY_CDCSS_BAUD_RATE                                   = 0x07U,
	REG_08_CDCSS_CALL_SYMBOL_NUMBER_AND_COEFFICIENT                        = 0x08U,
	REG_09                                                                 = 0x09U,
	REG_0B_FSK_STATUS                                                      = 0x0BU,
	REG_0C_CDCSS_CTCSS_STATUS_VOX_SQ_INTR_INDICATOR                        = 0x0CU,
	REG_0D_FREQUENCY_SCAN_INDICATOR_FREQ_HIGH                              = 0x0DU,
	REG_0E_FREQUENCY_SCAN_FREQ_LOW                                         = 0x0EU,
	REG_10                                                                 = 0x10U,
	REG_11                                                                 = 0x11U,
	REG_12                                                                 = 0x12U,
	REG_13                                                                 = 0x13U,
	REG_14                                                                 = 0x14U,
	REG_19                                                                 = 0x19U,
	REG_1F                                                                 = 0x1FU,
	REG_20                                                                 = 0x20U,
	REG_24_DTMF_SELCALL_CONFIG                                             = 0x24U,
	REG_28_EXPANDER_CONFIG                                                 = 0x28U,
	REG_29_COMPRESS_CONFIG                                                 = 0x29U,
	REG_2B_AF_FILTER_DISABLE                                               = 0x2BU,
	REG_30_VARIOUS_ENABLE_BITS                                             = 0x30U,
	REG_31_ENABLE_COMPANDER_VOX_SCRAMBLE                                   = 0x31U,
	REG_32_FREQUENCY_SCAN                                                  = 0x32U,
	REG_33                                                                 = 0x33U,
	REG_36_POWER_AMPLIFIER_BIAS_AND_GAIN                                   = 0x36U,
	REG_37_VOLTATE_LDO_AND_MISC_ENABLE                                     = 0x37U,
	REG_38_FREQUENCY_LOW                                                   = 0x38U,
	REG_39_FREQUENCY_HIGH                                                  = 0x39U,
	REG_3A_RSSI_THRESHOLD_FOR_SQ1_SQ0                                      = 0x3AU,
	REG_3B_XTAL_FREQ_LOW                                                   = 0x3BU,
	REG_3C_XTAL_FREQ_HIGH                                                  = 0x3CU,
	REG_3E                                                                 = 0x3EU,
	REG_3F_INTERRUPT_ENABLE                                                = 0x3FU,
	REG_43_RF_AFT_LPF2_FILTER_BANDWIDTH                                    = 0x43U,
	REG_46_VOICE_AMPLITUDE_THRESHOLD_VOX1                                  = 0x46U,
	REG_48_AF_RF_GAIN_DAC_GAIN                                             = 0x48U,
	REG_49                                                                 = 0x49U,
	REG_4D_GLITCH_THR_SQ0                                                  = 0x4DU,
	REG_4E_SQ1_DELAY_SQ0_DELAY_GLITCH_THR_SQ1                              = 0x4EU,
	REG_4F_EXNOISE_THR_SQ0_EXNOISE_THR_SQ1                                 = 0x4FU,
	REG_51_CTCSS_CDCSS_CONFIG                                              = 0x51U,
	REG_58_FSK_CONFIG_BITS                                                 = 0x58U,
	REG_59_VARIOUS_FSK_ENABLE_AND_CONFIG_BITS                              = 0x59U,
	REG_5A_FSK_SYNC_BYTES_0_1                                              = 0x5AU,
	REG_5B_FSK_SYNC_BYTES_2_3                                              = 0x5BU,
	REG_5C_CRC_ENABLE_AND_UNKNOWN_BITS                                     = 0x5CU,
	REG_5D_FSK_DATA_LENGTH                                                 = 0x5DU,
	REG_5F_FSK_WORD_INPUT_OUTPUT                                           = 0x5FU,
	REG_64_VOXAMP                                                          = 0x64U,
	REG_67_RSSI                                                            = 0x67U,
	REG_68_CTCSS_SCAN_INDICATOR_FREQ                                       = 0x68U,
	REG_69_CDCSS_SCAN_INDICATOR_FREQ_HIGH                                  = 0x69U,
	REG_6A_CDCSS_SCAN_FREQ_LOW                                             = 0x6AU,
	REG_6F_AF_TX_RX_INPUT_AMPLITUDE                                        = 0x6FU,
	REG_70_TONE1_CONFIG                                                    = 0x70U,
	REG_71_TONE1_SCRAMBLE_FREQ_CONTROL_WORD                                = 0x71U,
	REG_72_TONE2_FSK_FREQUENCY_CONTROL_WORD                                = 0x72U,
	REG_79_VOX1_DETECTION_INTERVAL_TIME_VOICE_AMPLITUDE_THRESHOLD_VOX0     = 0x79U,
	REG_7A_VOX0_DETECTION_DELAY                                            = 0x7AU,
	REG_7B                                                                 = 0x7BU,
	REG_7C                                                                 = 0x7CU,
	REG_7D_MIC_SENSITIVITY_TUNING                                          = 0x7DU,
	REG_7E_DC_FILTER_BANDWIDTH_AND_AGC_FIX                                 = 0x7EU,
};

typedef enum BK4819_REGISTER_t BK4819_REGISTER_t;

#endif

